workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Make gradlew executable
        script: | 
          chmod +x gradlew
      - name: Build Android debug APK
        script: | 
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - prakashbhapra@gmail.com
        notify:
          success: true
          failure: true
